title: Bloodline's Blog
url: 'http://www.ibloodline.com'
description: 'Notes and thoughts from Bloodline'
baseurl : ''
exclude: [Gemfile, Gemfile.lock, README.md]

# Conversion
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  extensions: [ "fenced_code_blocks", "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]

author: 'Tony Han'
disqus_shortname: Bloodline
google_analytics: UA-73798612-1

plugins:
  # https://help.github.com/articles/atom-rss-feeds-for-github-pages/
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10 # 指定每页多少条
paginate_path: "/blog/page:num" # 指定每页的url

sass:
    sass_dir: _sass
    style: :compressed

disqus_shortname : ibloodline

timezone: Toronto

encoding : utf-8